def operations1(num1, num2):
    op = input("Operation (+, -, /, *): ")
    if op == '+': print("Result: ", float(num1) + float(num2))
    elif op == '-': print("Result: ", float(num1) - float(num2))
    elif op == '/': print("Result: ", float(num1) / float(num2))
    elif op == '*': print("Result: ", float(num1) * float(num2))
    else: print("Invalid operation")
def operations2(num1, num2, num3):
    print("Now doing all possible calculations with", num1, num2, "and", num3)
    wait = input("Press enter to continue")
    print(num1, "+", num2, "+", num3, "=", float(num1) + float(num2) + float(num3))
    print(num1, "+", num2, "-", num3, "=", float(num1) + float(num2) - float(num3))
    print(num1, "+", num2, "*", num3, "=", float(num1) + float(num2) * float(num3))
    print(num1, "+", num2, "/", num3, "=", float(num1) + float(num2) / float(num3))
    print(num1, "-", num2, "+", num3, "=", float(num1) - float(num2) + float(num3))
    print(num1, "-", num2, "-", num3, "=", float(num1) - float(num2) - float(num3))
    print(num1, "-", num2, "*", num3, "=", float(num1) - float(num2) * float(num3))
    print(num1, "-", num2, "/", num3, "=", float(num1) - float(num2) / float(num3))
    print(num1, "*", num2, "+", num3, "=", float(num1) * float(num2) + float(num3))
    print(num1, "*", num2, "-", num3, "=", float(num1) * float(num2) - float(num3))
    print(num1, "*", num2, "*", num3, "=", float(num1) * float(num2) * float(num3))
    print(num1, "*", num2, "/", num3, "=", float(num1) * float(num2) / float(num3))
    print(num1, "/", num2, "+", num3, "=", float(num1) / float(num2) + float(num3))
    print(num1, "/", num2, "-", num3, "=", float(num1) / float(num2) - float(num3))
    print(num1, "/", num2, "*", num3, "=", float(num1) / float(num2) * float(num3))
    print(num1, "/", num2, "/", num3, "=", float(num1) / float(num2) / float(num3))
    exit()
def operations3(num1, num2, num3, num4):
    print("Now doing all possible calculations with", num1, num2, num3, "and", num4)
    wait = input("Press enter to continue")
    print("Addition")
    print(num1, "+", num2, "+", num3, "+", num4, "=", float(num1) + float(num2) + float(num3) + float(num4))
    print(num1, "+", num2, "+", num3, "-", num4, "=", float(num1) + float(num2) + float(num3) - float(num4))
    print(num1, "+", num2, "+", num3, "*", num4, "=", float(num1) + float(num2) + float(num3) * float(num4))
    print(num1, "+", num2, "+", num3, "/", num4, "=", float(num1) + float(num2) + float(num3) / float(num4))
    print(num1, "+", num2, "-", num3, "+", num4, "=", float(num1) + float(num2) - float(num3) + float(num4))
    print(num1, "+", num2, "-", num3, "-", num4, "=", float(num1) + float(num2) - float(num3) - float(num4))
    print(num1, "+", num2, "-", num3, "*", num4, "=", float(num1) + float(num2) - float(num3) * float(num4))
    print(num1, "+", num2, "-", num3, "/", num4, "=", float(num1) + float(num2) - float(num3) / float(num4))
    print(num1, "+", num2, "*", num3, "+", num4, "=", float(num1) + float(num2) * float(num3) + float(num4))
    print(num1, "+", num2, "*", num3, "-", num4, "=", float(num1) + float(num2) * float(num3) - float(num4))
    print(num1, "+", num2, "*", num3, "*", num4, "=", float(num1) + float(num2) * float(num3) * float(num4))
    print(num1, "+", num2, "*", num3, "/", num4, "=", float(num1) + float(num2) * float(num3) / float(num4))
    print(num1, "+", num2, "/", num3, "+", num4, "=", float(num1) + float(num2) / float(num3) + float(num4))
    print(num1, "+", num2, "/", num3, "-", num4, "=", float(num1) + float(num2) / float(num3) - float(num4))
    print(num1, "+", num2, "/", num3, "*", num4, "=", float(num1) + float(num2) / float(num3) * float(num4))
    print(num1, "+", num2, "/", num3, "/", num4, "=", float(num1) + float(num2) / float(num3) / float(num4))
    print("Subtraction")
    print(num1, "-", num2, "+", num3, "+", num4, "=", float(num1) - float(num2) + float(num3) + float(num4))
    print(num1, "-", num2, "+", num3, "-", num4, "=", float(num1) - float(num2) + float(num3) - float(num4))
    print(num1, "-", num2, "+", num3, "*", num4, "=", float(num1) - float(num2) + float(num3) * float(num4))
    print(num1, "-", num2, "+", num3, "/", num4, "=", float(num1) - float(num2) + float(num3) / float(num4))
    print(num1, "-", num2, "-", num3, "+", num4, "=", float(num1) - float(num2) - float(num3) + float(num4))
    print(num1, "-", num2, "-", num3, "-", num4, "=", float(num1) - float(num2) - float(num3) - float(num4))
    print(num1, "-", num2, "-", num3, "*", num4, "=", float(num1) - float(num2) - float(num3) * float(num4))
    print(num1, "-", num2, "-", num3, "/", num4, "=", float(num1) - float(num2) - float(num3) / float(num4))
    print(num1, "-", num2, "*", num3, "+", num4, "=", float(num1) - float(num2) * float(num3) + float(num4))
    print(num1, "-", num2, "*", num3, "-", num4, "=", float(num1) - float(num2) * float(num3) - float(num4))
    print(num1, "-", num2, "*", num3, "*", num4, "=", float(num1) - float(num2) * float(num3) * float(num4))
    print(num1, "-", num2, "*", num3, "/", num4, "=", float(num1) - float(num2) * float(num3) / float(num4))
    print(num1, "-", num2, "/", num3, "+", num4, "=", float(num1) - float(num2) / float(num3) + float(num4))
    print(num1, "-", num2, "/", num3, "-", num4, "=", float(num1) - float(num2) / float(num3) - float(num4))
    print(num1, "-", num2, "/", num3, "*", num4, "=", float(num1) - float(num2) / float(num3) * float(num4))
    print(num1, "-", num2, "/", num3, "/", num4, "=", float(num1) - float(num2) / float(num3) / float(num4))
    print("Multiplication")
    print(num1, "*", num2, "+", num3, "+", num4, "=", float(num1) * float(num2) + float(num3) + float(num4))
    print(num1, "*", num2, "+", num3, "-", num4, "=", float(num1) * float(num2) + float(num3) - float(num4))
    print(num1, "*", num2, "+", num3, "*", num4, "=", float(num1) * float(num2) + float(num3) * float(num4))
    print(num1, "*", num2, "+", num3, "/", num4, "=", float(num1) * float(num2) + float(num3) / float(num4))
    print(num1, "*", num2, "-", num3, "+", num4, "=", float(num1) * float(num2) - float(num3) + float(num4))
    print(num1, "*", num2, "-", num3, "-", num4, "=", float(num1) * float(num2) - float(num3) - float(num4))
    print(num1, "*", num2, "-", num3, "*", num4, "=", float(num1) * float(num2) - float(num3) * float(num4))
    print(num1, "*", num2, "-", num3, "/", num4, "=", float(num1) * float(num2) - float(num3) / float(num4))
    print(num1, "*", num2, "*", num3, "+", num4, "=", float(num1) * float(num2) * float(num3) + float(num4))
    print(num1, "*", num2, "*", num3, "-", num4, "=", float(num1) * float(num2) * float(num3) - float(num4))
    print(num1, "*", num2, "*", num3, "*", num4, "=", float(num1) * float(num2) * float(num3) * float(num4))
    print(num1, "*", num2, "*", num3, "/", num4, "=", float(num1) * float(num2) * float(num3) / float(num4))
    print(num1, "*", num2, "/", num3, "+", num4, "=", float(num1) * float(num2) / float(num3) + float(num4))
    print(num1, "*", num2, "/", num3, "-", num4, "=", float(num1) * float(num2) / float(num3) - float(num4))
    print(num1, "*", num2, "/", num3, "*", num4, "=", float(num1) * float(num2) / float(num3) * float(num4))
    print(num1, "*", num2, "/", num3, "/", num4, "=", float(num1) * float(num2) / float(num3) / float(num4))
    print("Division")
    print(num1, "/", num2, "+", num3, "+", num4, "=", float(num1) / float(num2) + float(num3) + float(num4))
    print(num1, "/", num2, "+", num3, "-", num4, "=", float(num1) / float(num2) + float(num3) - float(num4))
    print(num1, "/", num2, "+", num3, "*", num4, "=", float(num1) / float(num2) + float(num3) * float(num4))
    print(num1, "/", num2, "+", num3, "/", num4, "=", float(num1) / float(num2) + float(num3) / float(num4))
    print(num1, "/", num2, "-", num3, "+", num4, "=", float(num1) / float(num2) - float(num3) + float(num4))
    print(num1, "/", num2, "-", num3, "-", num4, "=", float(num1) / float(num2) - float(num3) - float(num4))
    print(num1, "/", num2, "-", num3, "*", num4, "=", float(num1) / float(num2) - float(num3) * float(num4))
    print(num1, "/", num2, "-", num3, "/", num4, "=", float(num1) / float(num2) - float(num3) / float(num4))
    print(num1, "/", num2, "*", num3, "+", num4, "=", float(num1) / float(num2) * float(num3) + float(num4))
    print(num1, "/", num2, "*", num3, "-", num4, "=", float(num1) / float(num2) * float(num3) - float(num4))
    print(num1, "/", num2, "*", num3, "*", num4, "=", float(num1) / float(num2) * float(num3) * float(num4))
    print(num1, "/", num2, "*", num3, "/", num4, "=", float(num1) / float(num2) * float(num3) / float(num4))
    print(num1, "/", num2, "/", num3, "+", num4, "=", float(num1) / float(num2) / float(num3) + float(num4))
    print(num1, "/", num2, "/", num3, "-", num4, "=", float(num1) / float(num2) / float(num3) - float(num4))
    print(num1, "/", num2, "/", num3, "*", num4, "=", float(num1) / float(num2) / float(num3) * float(num4))
    print(num1, "/", num2, "/", num3, "/", num4, "=", float(num1) / float(num2) / float(num3) / float(num4))
    exit()

def operations4(num1, num2, num3, num4, num5):
    print("Now doing all possible calculations with", num1, num2, num3, num4, "and", num5)
    wait = input("Press enter to continue")
    print("Addition")
    print(num1, "+", num2, "+", num3, "+", num4, "+", num5, "=", float(num1) + float(num2) + float(num3) + float(num4) + float(num5))
    print(num1, "+", num2, "+", num3, "+", num4, "-", num5, "=", float(num1) + float(num2) + float(num3) + float(num4) - float(num5))
    print(num1, "+", num2, "+", num3, "+", num4, "*", num5, "=", float(num1) + float(num2) + float(num3) + float(num4) * float(num5))
    print(num1, "+", num2, "+", num3, "+", num4, "/", num5, "=", float(num1) + float(num2) + float(num3) + float(num4) / float(num5))
    print(num1, "+", num2, "+", num3, "-", num4, "+", num5, "=", float(num1) + float(num2) + float(num3) - float(num4) + float(num5))
    print(num1, "+", num2, "+", num3, "-", num4, "-", num5, "=", float(num1) + float(num2) + float(num3) - float(num4) - float(num5))
    print(num1, "+", num2, "+", num3, "-", num4, "*", num5, "=", float(num1) + float(num2) + float(num3) - float(num4) * float(num5))
    print(num1, "+", num2, "+", num3, "-", num4, "/", num5, "=", float(num1) + float(num2) + float(num3) - float(num4) / float(num5))
    print(num1, "+", num2, "+", num3, "*", num4, "+", num5, "=", float(num1) + float(num2) + float(num3) * float(num4) + float(num5))
    print(num1, "+", num2, "+", num3, "*", num4, "-", num5, "=", float(num1) + float(num2) + float(num3) * float(num4) - float(num5))
    print(num1, "+", num2, "+", num3, "*", num4, "*", num5, "=", float(num1) + float(num2) + float(num3) * float(num4) * float(num5))
    print(num1, "+", num2, "+", num3, "*", num4, "/", num5, "=", float(num1) + float(num2) + float(num3) * float(num4) / float(num5))
    print(num1, "+", num2, "+", num3, "/", num4, "+", num5, "=", float(num1) + float(num2) + float(num3) / float(num4) + float(num5))
    print(num1, "+", num2, "+", num3, "/", num4, "-", num5, "=", float(num1) + float(num2) + float(num3) / float(num4) - float(num5))
    print(num1, "+", num2, "+", num3, "/", num4, "*", num5, "=", float(num1) + float(num2) + float(num3) / float(num4) * float(num5))
    print(num1, "+", num2, "+", num3, "/", num4, "/", num5, "=", float(num1) + float(num2) + float(num3) / float(num4) / float(num5))
    print(num1, "+", num2, "-", num3, "+", num4, "+", num5, "=", float(num1) + float(num2) - float(num3) + float(num4) + float(num5))
    print(num1, "+", num2, "-", num3, "+", num4, "-", num5, "=", float(num1) + float(num2) - float(num3) + float(num4) - float(num5))
    print(num1, "+", num2, "-", num3, "+", num4, "*", num5, "=", float(num1) + float(num2) - float(num3) + float(num4) * float(num5))
    print(num1, "+", num2, "-", num3, "+", num4, "/", num5, "=", float(num1) + float(num2) - float(num3) + float(num4) / float(num5))
    print(num1, "+", num2, "-", num3, "-", num4, "+", num5, "=", float(num1) + float(num2) - float(num3) - float(num4) + float(num5))
    print(num1, "+", num2, "-", num3, "-", num4, "-", num5, "=", float(num1) + float(num2) - float(num3) - float(num4) - float(num5))
    print(num1, "+", num2, "-", num3, "-", num4, "*", num5, "=", float(num1) + float(num2) - float(num3) - float(num4) * float(num5))
    print(num1, "+", num2, "-", num3, "-", num4, "/", num5, "=", float(num1) + float(num2) - float(num3) - float(num4) / float(num5))
    print(num1, "+", num2, "-", num3, "*", num4, "+", num5, "=", float(num1) + float(num2) - float(num3) * float(num4) + float(num5))
    print(num1, "+", num2, "-", num3, "*", num4, "-", num5, "=", float(num1) + float(num2) - float(num3) * float(num4) - float(num5))
    print(num1, "+", num2, "-", num3, "*", num4, "*", num5, "=", float(num1) + float(num2) - float(num3) * float(num4) * float(num5))
    print(num1, "+", num2, "-", num3, "*", num4, "/", num5, "=", float(num1) + float(num2) - float(num3) * float(num4) / float(num5))
    print(num1, "+", num2, "-", num3, "/", num4, "+", num5, "=", float(num1) + float(num2) - float(num3) / float(num4) + float(num5))
    print(num1, "+", num2, "-", num3, "/", num4, "-", num5, "=", float(num1) + float(num2) - float(num3) / float(num4) - float(num5))
    print(num1, "+", num2, "-", num3, "/", num4, "*", num5, "=", float(num1) + float(num2) - float(num3) / float(num4) * float(num5))
    print(num1, "+", num2, "-", num3, "/", num4, "/", num5, "=", float(num1) + float(num2) - float(num3) / float(num4) / float(num5))
    print(num1, "+", num2, "*", num3, "+", num4, "+", num5, "=", float(num1) + float(num2) * float(num3) + float(num4) + float(num5))
    print(num1, "+", num2, "*", num3, "+", num4, "-", num5, "=", float(num1) + float(num2) * float(num3) + float(num4) - float(num5))
    print(num1, "+", num2, "*", num3, "+", num4, "*", num5, "=", float(num1) + float(num2) * float(num3) + float(num4) * float(num5))
    print(num1, "+", num2, "*", num3, "+", num4, "/", num5, "=", float(num1) + float(num2) * float(num3) + float(num4) / float(num5))
    print(num1, "+", num2, "*", num3, "-", num4, "+", num5, "=", float(num1) + float(num2) * float(num3) - float(num4) + float(num5))
    print(num1, "+", num2, "*", num3, "-", num4, "-", num5, "=", float(num1) + float(num2) * float(num3) - float(num4) - float(num5))
    print(num1, "+", num2, "*", num3, "-", num4, "*", num5, "=", float(num1) + float(num2) * float(num3) - float(num4) * float(num5))
    print(num1, "+", num2, "*", num3, "-", num4, "/", num5, "=", float(num1) + float(num2) * float(num3) - float(num4) / float(num5))
    print(num1, "+", num2, "*", num3, "*", num4, "+", num5, "=", float(num1) + float(num2) * float(num3) * float(num4) + float(num5))
    print(num1, "+", num2, "*", num3, "*", num4, "-", num5, "=", float(num1) + float(num2) * float(num3) * float(num4) - float(num5))
    print(num1, "+", num2, "*", num3, "*", num4, "*", num5, "=", float(num1) + float(num2) * float(num3) * float(num4) * float(num5))
    print(num1, "+", num2, "*", num3, "*", num4, "/", num5, "=", float(num1) + float(num2) * float(num3) * float(num4) / float(num5))
    print(num1, "+", num2, "*", num3, "/", num4, "+", num5, "=", float(num1) + float(num2) * float(num3) / float(num4) + float(num5))
    print(num1, "+", num2, "*", num3, "/", num4, "-", num5, "=", float(num1) + float(num2) * float(num3) / float(num4) - float(num5))
    print(num1, "+", num2, "*", num3, "/", num4, "*", num5, "=", float(num1) + float(num2) * float(num3) / float(num4) * float(num5))
    print(num1, "+", num2, "*", num3, "/", num4, "/", num5, "=", float(num1) + float(num2) * float(num3) / float(num4) / float(num5))
    print(num1, "+", num2, "/", num3, "+", num4, "+", num5, "=", float(num1) + float(num2) / float(num3) + float(num4) + float(num5))
    print(num1, "+", num2, "/", num3, "+", num4, "-", num5, "=", float(num1) + float(num2) / float(num3) + float(num4) - float(num5))
    print(num1, "+", num2, "/", num3, "+", num4, "*", num5, "=", float(num1) + float(num2) / float(num3) + float(num4) * float(num5))
    print(num1, "+", num2, "/", num3, "+", num4, "/", num5, "=", float(num1) + float(num2) / float(num3) + float(num4) / float(num5))
    print(num1, "+", num2, "/", num3, "-", num4, "+", num5, "=", float(num1) + float(num2) / float(num3) - float(num4) + float(num5))
    print(num1, "+", num2, "/", num3, "-", num4, "-", num5, "=", float(num1) + float(num2) / float(num3) - float(num4) - float(num5))
    print(num1, "+", num2, "/", num3, "-", num4, "*", num5, "=", float(num1) + float(num2) / float(num3) - float(num4) * float(num5))
    print(num1, "+", num2, "/", num3, "-", num4, "/", num5, "=", float(num1) + float(num2) / float(num3) - float(num4) / float(num5))
    print(num1, "+", num2, "/", num3, "*", num4, "+", num5, "=", float(num1) + float(num2) / float(num3) * float(num4) + float(num5))
    print(num1, "+", num2, "/", num3, "*", num4, "-", num5, "=", float(num1) + float(num2) / float(num3) * float(num4) - float(num5))
    print(num1, "+", num2, "/", num3, "*", num4, "*", num5, "=", float(num1) + float(num2) / float(num3) * float(num4) * float(num5))
    print(num1, "+", num2, "/", num3, "*", num4, "/", num5, "=", float(num1) + float(num2) / float(num3) * float(num4) / float(num5))
    print(num1, "+", num2, "/", num3, "/", num4, "+", num5, "=", float(num1) + float(num2) / float(num3) / float(num4) + float(num5))
    print(num1, "+", num2, "/", num3, "/", num4, "-", num5, "=", float(num1) + float(num2) / float(num3) / float(num4) - float(num5))
    print(num1, "+", num2, "/", num3, "/", num4, "*", num5, "=", float(num1) + float(num2) / float(num3) / float(num4) * float(num5))
    print(num1, "+", num2, "/", num3, "/", num4, "/", num5, "=", float(num1) + float(num2) / float(num3) / float(num4) / float(num5))
    print("Subtraction")
    print(num1, "-", num2, "+", num3, "+", num4, "+", num5, "=", float(num1) - float(num2) + float(num3) + float(num4) + float(num5))
    print(num1, "-", num2, "+", num3, "+", num4, "-", num5, "=", float(num1) - float(num2) + float(num3) + float(num4) - float(num5))
    print(num1, "-", num2, "+", num3, "+", num4, "*", num5, "=", float(num1) - float(num2) + float(num3) + float(num4) * float(num5))
    print(num1, "-", num2, "+", num3, "+", num4, "/", num5, "=", float(num1) - float(num2) + float(num3) + float(num4) / float(num5))
    print(num1, "-", num2, "+", num3, "-", num4, "+", num5, "=", float(num1) - float(num2) + float(num3) - float(num4) + float(num5))
    print(num1, "-", num2, "+", num3, "-", num4, "-", num5, "=", float(num1) - float(num2) + float(num3) - float(num4) - float(num5))
    print(num1, "-", num2, "+", num3, "-", num4, "*", num5, "=", float(num1) - float(num2) + float(num3) - float(num4) * float(num5))
    print(num1, "-", num2, "+", num3, "-", num4, "/", num5, "=", float(num1) - float(num2) + float(num3) - float(num4) / float(num5))
    print(num1, "-", num2, "+", num3, "*", num4, "+", num5, "=", float(num1) - float(num2) + float(num3) * float(num4) + float(num5))
    print(num1, "-", num2, "+", num3, "*", num4, "-", num5, "=", float(num1) - float(num2) + float(num3) * float(num4) - float(num5))
    print(num1, "-", num2, "+", num3, "*", num4, "*", num5, "=", float(num1) - float(num2) + float(num3) * float(num4) * float(num5))
    print(num1, "-", num2, "+", num3, "*", num4, "/", num5, "=", float(num1) - float(num2) + float(num3) * float(num4) / float(num5))
    print(num1, "-", num2, "+", num3, "/", num4, "+", num5, "=", float(num1) - float(num2) + float(num3) / float(num4) + float(num5))
    print(num1, "-", num2, "+", num3, "/", num4, "-", num5, "=", float(num1) - float(num2) + float(num3) / float(num4) - float(num5))
    print(num1, "-", num2, "+", num3, "/", num4, "*", num5, "=", float(num1) - float(num2) + float(num3) / float(num4) * float(num5))
    print(num1, "-", num2, "+", num3, "/", num4, "/", num5, "=", float(num1) - float(num2) + float(num3) / float(num4) / float(num5))
    print(num1, "-", num2, "-", num3, "+", num4, "+", num5, "=", float(num1) - float(num2) - float(num3) + float(num4) + float(num5))
    print(num1, "-", num2, "-", num3, "+", num4, "-", num5, "=", float(num1) - float(num2) - float(num3) + float(num4) - float(num5))
    print(num1, "-", num2, "-", num3, "+", num4, "*", num5, "=", float(num1) - float(num2) - float(num3) + float(num4) * float(num5))
    print(num1, "-", num2, "-", num3, "+", num4, "/", num5, "=", float(num1) - float(num2) - float(num3) + float(num4) / float(num5))
    print(num1, "-", num2, "-", num3, "-", num4, "+", num5, "=", float(num1) - float(num2) - float(num3) - float(num4) + float(num5))
    print(num1, "-", num2, "-", num3, "-", num4, "-", num5, "=", float(num1) - float(num2) - float(num3) - float(num4) - float(num5))
    print(num1, "-", num2, "-", num3, "-", num4, "*", num5, "=", float(num1) - float(num2) - float(num3) - float(num4) * float(num5))
    print(num1, "-", num2, "-", num3, "-", num4, "/", num5, "=", float(num1) - float(num2) - float(num3) - float(num4) / float(num5))
    print(num1, "-", num2, "-", num3, "*", num4, "+", num5, "=", float(num1) - float(num2) - float(num3) * float(num4) + float(num5))
    print(num1, "-", num2, "-", num3, "*", num4, "-", num5, "=", float(num1) - float(num2) - float(num3) * float(num4) - float(num5))
    print(num1, "-", num2, "-", num3, "*", num4, "*", num5, "=", float(num1) - float(num2) - float(num3) * float(num4) * float(num5))
    print(num1, "-", num2, "-", num3, "*", num4, "/", num5, "=", float(num1) - float(num2) - float(num3) * float(num4) / float(num5))
    print(num1, "-", num2, "-", num3, "/", num4, "+", num5, "=", float(num1) - float(num2) - float(num3) / float(num4) + float(num5))
    print(num1, "-", num2, "-", num3, "/", num4, "-", num5, "=", float(num1) - float(num2) - float(num3) / float(num4) - float(num5))
    print(num1, "-", num2, "-", num3, "/", num4, "*", num5, "=", float(num1) - float(num2) - float(num3) / float(num4) * float(num5))
    print(num1, "-", num2, "-", num3, "/", num4, "/", num5, "=", float(num1) - float(num2) - float(num3) / float(num4) / float(num5))
    print(num1, "-", num2, "*", num3, "+", num4, "+", num5, "=", float(num1) - float(num2) * float(num3) + float(num4) + float(num5))
    print(num1, "-", num2, "*", num3, "+", num4, "-", num5, "=", float(num1) - float(num2) * float(num3) + float(num4) - float(num5))
    print(num1, "-", num2, "*", num3, "+", num4, "*", num5, "=", float(num1) - float(num2) * float(num3) + float(num4) * float(num5))
    print(num1, "-", num2, "*", num3, "+", num4, "/", num5, "=", float(num1) - float(num2) * float(num3) + float(num4) / float(num5))
    print(num1, "-", num2, "*", num3, "-", num4, "+", num5, "=", float(num1) - float(num2) * float(num3) - float(num4) + float(num5))
    print(num1, "-", num2, "*", num3, "-", num4, "-", num5, "=", float(num1) - float(num2) * float(num3) - float(num4) - float(num5))
    print(num1, "-", num2, "*", num3, "-", num4, "*", num5, "=", float(num1) - float(num2) * float(num3) - float(num4) * float(num5))
    print(num1, "-", num2, "*", num3, "-", num4, "/", num5, "=", float(num1) - float(num2) * float(num3) - float(num4) / float(num5))
    print(num1, "-", num2, "*", num3, "*", num4, "+", num5, "=", float(num1) - float(num2) * float(num3) * float(num4) + float(num5))
    print(num1, "-", num2, "*", num3, "*", num4, "-", num5, "=", float(num1) - float(num2) * float(num3) * float(num4) - float(num5))
    print(num1, "-", num2, "*", num3, "*", num4, "*", num5, "=", float(num1) - float(num2) * float(num3) * float(num4) * float(num5))
    print(num1, "-", num2, "*", num3, "*", num4, "/", num5, "=", float(num1) - float(num2) * float(num3) * float(num4) / float(num5))
    print(num1, "-", num2, "*", num3, "/", num4, "+", num5, "=", float(num1) - float(num2) * float(num3) / float(num4) + float(num5))
    print(num1, "-", num2, "*", num3, "/", num4, "-", num5, "=", float(num1) - float(num2) * float(num3) / float(num4) - float(num5))
    print(num1, "-", num2, "*", num3, "/", num4, "*", num5, "=", float(num1) - float(num2) * float(num3) / float(num4) * float(num5))
    print(num1, "-", num2, "*", num3, "/", num4, "/", num5, "=", float(num1) - float(num2) * float(num3) / float(num4) / float(num5))
    print(num1, "-", num2, "/", num3, "+", num4, "+", num5, "=", float(num1) - float(num2) / float(num3) + float(num4) + float(num5))
    print(num1, "-", num2, "/", num3, "+", num4, "-", num5, "=", float(num1) - float(num2) / float(num3) + float(num4) - float(num5))
    print(num1, "-", num2, "/", num3, "+", num4, "*", num5, "=", float(num1) - float(num2) / float(num3) + float(num4) * float(num5))
    print(num1, "-", num2, "/", num3, "+", num4, "/", num5, "=", float(num1) - float(num2) / float(num3) + float(num4) / float(num5))
    print(num1, "-", num2, "/", num3, "-", num4, "+", num5, "=", float(num1) - float(num2) / float(num3) - float(num4) + float(num5))
    print(num1, "-", num2, "/", num3, "-", num4, "-", num5, "=", float(num1) - float(num2) / float(num3) - float(num4) - float(num5))
    print(num1, "-", num2, "/", num3, "-", num4, "*", num5, "=", float(num1) - float(num2) / float(num3) - float(num4) * float(num5))
    print(num1, "-", num2, "/", num3, "-", num4, "/", num5, "=", float(num1) - float(num2) / float(num3) - float(num4) / float(num5))
    print(num1, "-", num2, "/", num3, "*", num4, "+", num5, "=", float(num1) - float(num2) / float(num3) * float(num4) + float(num5))
    print(num1, "-", num2, "/", num3, "*", num4, "-", num5, "=", float(num1) - float(num2) / float(num3) * float(num4) - float(num5))
    print(num1, "-", num2, "/", num3, "*", num4, "*", num5, "=", float(num1) - float(num2) / float(num3) * float(num4) * float(num5))
    print(num1, "-", num2, "/", num3, "*", num4, "/", num5, "=", float(num1) - float(num2) / float(num3) * float(num4) / float(num5))
    print(num1, "-", num2, "/", num3, "/", num4, "+", num5, "=", float(num1) - float(num2) / float(num3) / float(num4) + float(num5))
    print(num1, "-", num2, "/", num3, "/", num4, "-", num5, "=", float(num1) - float(num2) / float(num3) / float(num4) - float(num5))
    print(num1, "-", num2, "/", num3, "/", num4, "*", num5, "=", float(num1) - float(num2) / float(num3) / float(num4) * float(num5))
    print(num1, "-", num2, "/", num3, "/", num4, "/", num5, "=", float(num1) - float(num2) / float(num3) / float(num4) / float(num5))
    print("Multiplication")
    print(num1, "*", num2, "+", num3, "+", num4, "+", num5, "=", float(num1) * float(num2) + float(num3) + float(num4) + float(num5))
    print(num1, "*", num2, "+", num3, "+", num4, "-", num5, "=", float(num1) * float(num2) + float(num3) + float(num4) - float(num5))
    print(num1, "*", num2, "+", num3, "+", num4, "*", num5, "=", float(num1) * float(num2) + float(num3) + float(num4) * float(num5))
    print(num1, "*", num2, "+", num3, "+", num4, "/", num5, "=", float(num1) * float(num2) + float(num3) + float(num4) / float(num5))
    print(num1, "*", num2, "+", num3, "-", num4, "+", num5, "=", float(num1) * float(num2) + float(num3) - float(num4) + float(num5))
    print(num1, "*", num2, "+", num3, "-", num4, "-", num5, "=", float(num1) * float(num2) + float(num3) - float(num4) - float(num5))
    print(num1, "*", num2, "+", num3, "-", num4, "*", num5, "=", float(num1) * float(num2) + float(num3) - float(num4) * float(num5))
    print(num1, "*", num2, "+", num3, "-", num4, "/", num5, "=", float(num1) * float(num2) + float(num3) - float(num4) / float(num5))
    print(num1, "*", num2, "+", num3, "*", num4, "+", num5, "=", float(num1) * float(num2) + float(num3) * float(num4) + float(num5))
    print(num1, "*", num2, "+", num3, "*", num4, "-", num5, "=", float(num1) * float(num2) + float(num3) * float(num4) - float(num5))
    print(num1, "*", num2, "+", num3, "*", num4, "*", num5, "=", float(num1) * float(num2) + float(num3) * float(num4) * float(num5))
    print(num1, "*", num2, "+", num3, "*", num4, "/", num5, "=", float(num1) * float(num2) + float(num3) * float(num4) / float(num5))
    print(num1, "*", num2, "+", num3, "/", num4, "+", num5, "=", float(num1) * float(num2) + float(num3) / float(num4) + float(num5))
    print(num1, "*", num2, "+", num3, "/", num4, "-", num5, "=", float(num1) * float(num2) + float(num3) / float(num4) - float(num5))
    print(num1, "*", num2, "+", num3, "/", num4, "*", num5, "=", float(num1) * float(num2) + float(num3) / float(num4) * float(num5))
    print(num1, "*", num2, "+", num3, "/", num4, "/", num5, "=", float(num1) * float(num2) + float(num3) / float(num4) / float(num5))
    print(num1, "*", num2, "-", num3, "+", num4, "+", num5, "=", float(num1) * float(num2) - float(num3) + float(num4) + float(num5))
    print(num1, "*", num2, "-", num3, "+", num4, "-", num5, "=", float(num1) * float(num2) - float(num3) + float(num4) - float(num5))
    print(num1, "*", num2, "-", num3, "+", num4, "*", num5, "=", float(num1) * float(num2) - float(num3) + float(num4) * float(num5))
    print(num1, "*", num2, "-", num3, "+", num4, "/", num5, "=", float(num1) * float(num2) - float(num3) + float(num4) / float(num5))
    print(num1, "*", num2, "-", num3, "-", num4, "+", num5, "=", float(num1) * float(num2) - float(num3) - float(num4) + float(num5))
    print(num1, "*", num2, "-", num3, "-", num4, "-", num5, "=", float(num1) * float(num2) - float(num3) - float(num4) - float(num5))
    print(num1, "*", num2, "-", num3, "-", num4, "*", num5, "=", float(num1) * float(num2) - float(num3) - float(num4) * float(num5))
    print(num1, "*", num2, "-", num3, "-", num4, "/", num5, "=", float(num1) * float(num2) - float(num3) - float(num4) / float(num5))
    print(num1, "*", num2, "-", num3, "*", num4, "+", num5, "=", float(num1) * float(num2) - float(num3) * float(num4) + float(num5))
    print(num1, "*", num2, "-", num3, "*", num4, "-", num5, "=", float(num1) * float(num2) - float(num3) * float(num4) - float(num5))
    print(num1, "*", num2, "-", num3, "*", num4, "*", num5, "=", float(num1) * float(num2) - float(num3) * float(num4) * float(num5))
    print(num1, "*", num2, "-", num3, "*", num4, "/", num5, "=", float(num1) * float(num2) - float(num3) * float(num4) / float(num5))
    print(num1, "*", num2, "-", num3, "/", num4, "+", num5, "=", float(num1) * float(num2) - float(num3) / float(num4) + float(num5))
    print(num1, "*", num2, "-", num3, "/", num4, "-", num5, "=", float(num1) * float(num2) - float(num3) / float(num4) - float(num5))
    print(num1, "*", num2, "-", num3, "/", num4, "*", num5, "=", float(num1) * float(num2) - float(num3) / float(num4) * float(num5))
    print(num1, "*", num2, "-", num3, "/", num4, "/", num5, "=", float(num1) * float(num2) - float(num3) / float(num4) / float(num5))
    print(num1, "*", num2, "*", num3, "+", num4, "+", num5, "=", float(num1) * float(num2) * float(num3) + float(num4) + float(num5))
    print(num1, "*", num2, "*", num3, "+", num4, "-", num5, "=", float(num1) * float(num2) * float(num3) + float(num4) - float(num5))
    print(num1, "*", num2, "*", num3, "+", num4, "*", num5, "=", float(num1) * float(num2) * float(num3) + float(num4) * float(num5))
    print(num1, "*", num2, "*", num3, "+", num4, "/", num5, "=", float(num1) * float(num2) * float(num3) + float(num4) / float(num5))
    print(num1, "*", num2, "*", num3, "-", num4, "+", num5, "=", float(num1) * float(num2) * float(num3) - float(num4) + float(num5))
    print(num1, "*", num2, "*", num3, "-", num4, "-", num5, "=", float(num1) * float(num2) * float(num3) - float(num4) - float(num5))
    print(num1, "*", num2, "*", num3, "-", num4, "*", num5, "=", float(num1) * float(num2) * float(num3) - float(num4) * float(num5))
    print(num1, "*", num2, "*", num3, "-", num4, "/", num5, "=", float(num1) * float(num2) * float(num3) - float(num4) / float(num5))
    print(num1, "*", num2, "*", num3, "*", num4, "+", num5, "=", float(num1) * float(num2) * float(num3) * float(num4) + float(num5))
    print(num1, "*", num2, "*", num3, "*", num4, "-", num5, "=", float(num1) * float(num2) * float(num3) * float(num4) - float(num5))
    print(num1, "*", num2, "*", num3, "*", num4, "*", num5, "=", float(num1) * float(num2) * float(num3) * float(num4) * float(num5))
    print(num1, "*", num2, "*", num3, "*", num4, "/", num5, "=", float(num1) * float(num2) * float(num3) * float(num4) / float(num5))
    print(num1, "*", num2, "*", num3, "/", num4, "+", num5, "=", float(num1) * float(num2) * float(num3) / float(num4) + float(num5))
    print(num1, "*", num2, "*", num3, "/", num4, "-", num5, "=", float(num1) * float(num2) * float(num3) / float(num4) - float(num5))
    print(num1, "*", num2, "*", num3, "/", num4, "*", num5, "=", float(num1) * float(num2) * float(num3) / float(num4) * float(num5))
    print(num1, "*", num2, "*", num3, "/", num4, "/", num5, "=", float(num1) * float(num2) * float(num3) / float(num4) / float(num5))
    print(num1, "*", num2, "/", num3, "+", num4, "+", num5, "=", float(num1) * float(num2) / float(num3) + float(num4) + float(num5))
    print(num1, "*", num2, "/", num3, "+", num4, "-", num5, "=", float(num1) * float(num2) / float(num3) + float(num4) - float(num5))
    print(num1, "*", num2, "/", num3, "+", num4, "*", num5, "=", float(num1) * float(num2) / float(num3) + float(num4) * float(num5))
    print(num1, "*", num2, "/", num3, "+", num4, "/", num5, "=", float(num1) * float(num2) / float(num3) + float(num4) / float(num5))
    print(num1, "*", num2, "/", num3, "-", num4, "+", num5, "=", float(num1) * float(num2) / float(num3) - float(num4) + float(num5))
    print(num1, "*", num2, "/", num3, "-", num4, "-", num5, "=", float(num1) * float(num2) / float(num3) - float(num4) - float(num5))
    print(num1, "*", num2, "/", num3, "-", num4, "*", num5, "=", float(num1) * float(num2) / float(num3) - float(num4) * float(num5))
    print(num1, "*", num2, "/", num3, "-", num4, "/", num5, "=", float(num1) * float(num2) / float(num3) - float(num4) / float(num5))
    print(num1, "*", num2, "/", num3, "*", num4, "+", num5, "=", float(num1) * float(num2) / float(num3) * float(num4) + float(num5))
    print(num1, "*", num2, "/", num3, "*", num4, "-", num5, "=", float(num1) * float(num2) / float(num3) * float(num4) - float(num5))
    print(num1, "*", num2, "/", num3, "*", num4, "*", num5, "=", float(num1) * float(num2) / float(num3) * float(num4) * float(num5))
    print(num1, "*", num2, "/", num3, "*", num4, "/", num5, "=", float(num1) * float(num2) / float(num3) * float(num4) / float(num5))
    print(num1, "*", num2, "/", num3, "/", num4, "+", num5, "=", float(num1) * float(num2) / float(num3) / float(num4) + float(num5))
    print(num1, "*", num2, "/", num3, "/", num4, "-", num5, "=", float(num1) * float(num2) / float(num3) / float(num4) - float(num5))
    print(num1, "*", num2, "/", num3, "/", num4, "*", num5, "=", float(num1) * float(num2) / float(num3) / float(num4) * float(num5))
    print(num1, "*", num2, "/", num3, "/", num4, "/", num5, "=", float(num1) * float(num2) / float(num3) / float(num4) / float(num5))
    print("Division")
    print(num1, "/", num2, "+", num3, "+", num4, "+", num5, "=", float(num1) / float(num2) + float(num3) + float(num4) + float(num5))
    print(num1, "/", num2, "+", num3, "+", num4, "-", num5, "=", float(num1) / float(num2) + float(num3) + float(num4) - float(num5))
    print(num1, "/", num2, "+", num3, "+", num4, "*", num5, "=", float(num1) / float(num2) + float(num3) + float(num4) * float(num5))
    print(num1, "/", num2, "+", num3, "+", num4, "/", num5, "=", float(num1) / float(num2) + float(num3) + float(num4) / float(num5))
    print(num1, "/", num2, "+", num3, "-", num4, "+", num5, "=", float(num1) / float(num2) + float(num3) - float(num4) + float(num5))
    print(num1, "/", num2, "+", num3, "-", num4, "-", num5, "=", float(num1) / float(num2) + float(num3) - float(num4) - float(num5))
    print(num1, "/", num2, "+", num3, "-", num4, "*", num5, "=", float(num1) / float(num2) + float(num3) - float(num4) * float(num5))
    print(num1, "/", num2, "+", num3, "-", num4, "/", num5, "=", float(num1) / float(num2) + float(num3) - float(num4) / float(num5))
    print(num1, "/", num2, "+", num3, "*", num4, "+", num5, "=", float(num1) / float(num2) + float(num3) * float(num4) + float(num5))
    print(num1, "/", num2, "+", num3, "*", num4, "-", num5, "=", float(num1) / float(num2) + float(num3) * float(num4) - float(num5))
    print(num1, "/", num2, "+", num3, "*", num4, "*", num5, "=", float(num1) / float(num2) + float(num3) * float(num4) * float(num5))
    print(num1, "/", num2, "+", num3, "*", num4, "/", num5, "=", float(num1) / float(num2) + float(num3) * float(num4) / float(num5))
    print(num1, "/", num2, "+", num3, "/", num4, "+", num5, "=", float(num1) / float(num2) + float(num3) / float(num4) + float(num5))
    print(num1, "/", num2, "+", num3, "/", num4, "-", num5, "=", float(num1) / float(num2) + float(num3) / float(num4) - float(num5))
    print(num1, "/", num2, "+", num3, "/", num4, "*", num5, "=", float(num1) / float(num2) + float(num3) / float(num4) * float(num5))
    print(num1, "/", num2, "+", num3, "/", num4, "/", num5, "=", float(num1) / float(num2) + float(num3) / float(num4) / float(num5))
    print(num1, "/", num2, "-", num3, "+", num4, "+", num5, "=", float(num1) / float(num2) - float(num3) + float(num4) + float(num5))
    print(num1, "/", num2, "-", num3, "+", num4, "-", num5, "=", float(num1) / float(num2) - float(num3) + float(num4) - float(num5))
    print(num1, "/", num2, "-", num3, "+", num4, "*", num5, "=", float(num1) / float(num2) - float(num3) + float(num4) * float(num5))
    print(num1, "/", num2, "-", num3, "+", num4, "/", num5, "=", float(num1) / float(num2) - float(num3) + float(num4) / float(num5))
    print(num1, "/", num2, "-", num3, "-", num4, "+", num5, "=", float(num1) / float(num2) - float(num3) - float(num4) + float(num5))
    print(num1, "/", num2, "-", num3, "-", num4, "-", num5, "=", float(num1) / float(num2) - float(num3) - float(num4) - float(num5))
    print(num1, "/", num2, "-", num3, "-", num4, "*", num5, "=", float(num1) / float(num2) - float(num3) - float(num4) * float(num5))
    print(num1, "/", num2, "-", num3, "-", num4, "/", num5, "=", float(num1) / float(num2) - float(num3) - float(num4) / float(num5))
    print(num1, "/", num2, "-", num3, "*", num4, "+", num5, "=", float(num1) / float(num2) - float(num3) * float(num4) + float(num5))
    print(num1, "/", num2, "-", num3, "*", num4, "-", num5, "=", float(num1) / float(num2) - float(num3) * float(num4) - float(num5))
    print(num1, "/", num2, "-", num3, "*", num4, "*", num5, "=", float(num1) / float(num2) - float(num3) * float(num4) * float(num5))
    print(num1, "/", num2, "-", num3, "*", num4, "/", num5, "=", float(num1) / float(num2) - float(num3) * float(num4) / float(num5))
    print(num1, "/", num2, "-", num3, "/", num4, "+", num5, "=", float(num1) / float(num2) - float(num3) / float(num4) + float(num5))
    print(num1, "/", num2, "-", num3, "/", num4, "-", num5, "=", float(num1) / float(num2) - float(num3) / float(num4) - float(num5))
    print(num1, "/", num2, "-", num3, "/", num4, "*", num5, "=", float(num1) / float(num2) - float(num3) / float(num4) * float(num5))
    print(num1, "/", num2, "-", num3, "/", num4, "/", num5, "=", float(num1) / float(num2) - float(num3) / float(num4) / float(num5))
    print(num1, "/", num2, "*", num3, "+", num4, "+", num5, "=", float(num1) / float(num2) * float(num3) + float(num4) + float(num5))
    print(num1, "/", num2, "*", num3, "+", num4, "-", num5, "=", float(num1) / float(num2) * float(num3) + float(num4) - float(num5))
    print(num1, "/", num2, "*", num3, "+", num4, "*", num5, "=", float(num1) / float(num2) * float(num3) + float(num4) * float(num5))
    print(num1, "/", num2, "*", num3, "+", num4, "/", num5, "=", float(num1) / float(num2) * float(num3) + float(num4) / float(num5))
    print(num1, "/", num2, "*", num3, "-", num4, "+", num5, "=", float(num1) / float(num2) * float(num3) - float(num4) + float(num5))
    print(num1, "/", num2, "*", num3, "-", num4, "-", num5, "=", float(num1) / float(num2) * float(num3) - float(num4) - float(num5))
    print(num1, "/", num2, "*", num3, "-", num4, "*", num5, "=", float(num1) / float(num2) * float(num3) - float(num4) * float(num5))
    print(num1, "/", num2, "*", num3, "-", num4, "/", num5, "=", float(num1) / float(num2) * float(num3) - float(num4) / float(num5))
    print(num1, "/", num2, "*", num3, "*", num4, "+", num5, "=", float(num1) / float(num2) * float(num3) * float(num4) + float(num5))
    print(num1, "/", num2, "*", num3, "*", num4, "-", num5, "=", float(num1) / float(num2) * float(num3) * float(num4) - float(num5))
    print(num1, "/", num2, "*", num3, "*", num4, "*", num5, "=", float(num1) / float(num2) * float(num3) * float(num4) * float(num5))
    print(num1, "/", num2, "*", num3, "*", num4, "/", num5, "=", float(num1) / float(num2) * float(num3) * float(num4) / float(num5))
    print(num1, "/", num2, "*", num3, "/", num4, "+", num5, "=", float(num1) / float(num2) * float(num3) / float(num4) + float(num5))
    print(num1, "/", num2, "*", num3, "/", num4, "-", num5, "=", float(num1) / float(num2) * float(num3) / float(num4) - float(num5))
    print(num1, "/", num2, "*", num3, "/", num4, "*", num5, "=", float(num1) / float(num2) * float(num3) / float(num4) * float(num5))
    print(num1, "/", num2, "*", num3, "/", num4, "/", num5, "=", float(num1) / float(num2) * float(num3) / float(num4) / float(num5))
    print(num1, "/", num2, "/", num3, "+", num4, "+", num5, "=", float(num1) / float(num2) / float(num3) + float(num4) + float(num5))
    print(num1, "/", num2, "/", num3, "+", num4, "-", num5, "=", float(num1) / float(num2) / float(num3) + float(num4) - float(num5))
    print(num1, "/", num2, "/", num3, "+", num4, "*", num5, "=", float(num1) / float(num2) / float(num3) + float(num4) * float(num5))
    print(num1, "/", num2, "/", num3, "+", num4, "/", num5, "=", float(num1) / float(num2) / float(num3) + float(num4) / float(num5))
    print(num1, "/", num2, "/", num3, "-", num4, "+", num5, "=", float(num1) / float(num2) / float(num3) - float(num4) + float(num5))
    print(num1, "/", num2, "/", num3, "-", num4, "-", num5, "=", float(num1) / float(num2) / float(num3) - float(num4) - float(num5))
    print(num1, "/", num2, "/", num3, "-", num4, "*", num5, "=", float(num1) / float(num2) / float(num3) - float(num4) * float(num5))
    print(num1, "/", num2, "/", num3, "-", num4, "/", num5, "=", float(num1) / float(num2) / float(num3) - float(num4) / float(num5))
    print(num1, "/", num2, "/", num3, "*", num4, "+", num5, "=", float(num1) / float(num2) / float(num3) * float(num4) + float(num5))
    print(num1, "/", num2, "/", num3, "*", num4, "-", num5, "=", float(num1) / float(num2) / float(num3) * float(num4) - float(num5))
    print(num1, "/", num2, "/", num3, "*", num4, "*", num5, "=", float(num1) / float(num2) / float(num3) * float(num4) * float(num5))
    print(num1, "/", num2, "/", num3, "*", num4, "/", num5, "=", float(num1) / float(num2) / float(num3) * float(num4) / float(num5))
    print(num1, "/", num2, "/", num3, "/", num4, "+", num5, "=", float(num1) / float(num2) / float(num3) / float(num4) + float(num5))
    print(num1, "/", num2, "/", num3, "/", num4, "-", num5, "=", float(num1) / float(num2) / float(num3) / float(num4) - float(num5))
    print(num1, "/", num2, "/", num3, "/", num4, "*", num5, "=", float(num1) / float(num2) / float(num3) / float(num4) * float(num5))
    print(num1, "/", num2, "/", num3, "/", num4, "/", num5, "=", float(num1) / float(num2) / float(num3) / float(num4) / float(num5))
    print("I'm not making a 6th number")

# The actual calculator code compared to the operations code

num1 = input("First number: ")
num2 = input("Second number: ")
q = input("Any others? (y/n): ")
if q == 'y':
    num3 = input("Third number: ")
    q = input("Any others? (y/n): ")
    if q == 'y':
        num4 = input("Fourth number: ")
        q = input("Any others? (y/n): ")
        if q == 'y':
            num5 = input("Fifth number: ")
            q = input("Any others? (y/n): ")
            if q == 'y':
                print("Too many numbers")
            elif q == 'n':
                operations4(num1, num2, num3, num4, num5)
        elif q == 'n':
            operations3(num1, num2, num3, num4)
    elif q == 'n':
        operations2(num1, num2, num3)
elif q == 'n':
    operations1(num1, num2)
